AWSTemplateFormatVersion: "2010-09-09"
Description: Sample S3 Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: training66bducksfbvasdjkbfhasdjbfet11jojo
